-- Query for the Shortest CITY Name
SELECT CITY, LENGTH(CITY) AS NameLength
FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1;

-- Query for the Longest CITY Name
SELECT CITY, LENGTH(CITY) AS NameLength
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY
LIMIT 1;